version: "3.8"

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80111:3000"
    volumes:
      - ./:/opt/docusaurus:ro
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    # command: ${DOCKER_COMMAND:-npm run serve -- --host 0.0.0.0 --no-open}