version: "3.8"

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:3000"
    volumes:
      - ./:/opt/docusaurus:ro
      - /opt/docusaurus/node_modules
      - /opt/docusaurus/.docusaurus
      - /opt/docusaurus/.cache-loader
      - /opt/docusaurus/build
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    command: nodemon --config nodemon.json