version: "3.8"

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:3000"
    volumes:
      - ./:/opt/docusaurus:ro
      - /opt/docusaurus/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    # command: ${DOCKER_COMMAND:-npm run serve -- --host 0.0.0.0 --no-open}